### ISSUE TITLE
[FE] 1-2 스프린트 (style)

### ISSUE THREAD

**Issue by kanghaeun** [JNU-econovation/econo-error#15]
## Description
- 캘린더의 전체적인 뼈대를 잡는다 
## To Do
- [x] 달력 크기 및 배치
- [x] 폰트 세팅
- [ ] button 스타일 속성 및 배치
- [x] 월표시 이동 화살표 배치
- [x] 주말 폰트 색상 빨간색
- [x] 오늘의 날짜 숫자 배경색을 포인트 컬러 색으로 변경
- [ ] event 생성시 배경 색상 부여
- [x] 로고 배치
- [x] 요일 한글로 표시

**Comment by mlnwns** [comment]
로고 배치 외에는 크게 수정 할 부분 없는거같아요! 작성해주셔서 감사합니다
